# Generated by Django 3.2 on 2022-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=100)),
                ('profile_url', models.CharField(max_length=100)),
                ('repos_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
        ),
    ]
