# Generated by Django 3.2 on 2022-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
