# Generated by Django 3.2 on 2022-02-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20220205_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='repos_url',
        ),
    ]
