# Generated by Django 4.0.1 on 2022-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_remove_candidate_repos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='repos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
