# Generated by Django 3.2 on 2022-02-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_candidate_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='repos',
        ),
    ]
