# Generated by Django 3.2 on 2022-02-06 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_remove_candidate_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='repos',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
